server.port=19999
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.max-file-size=100MB

logging.file.name=logs/logmaker.log
logging.level.me.blueat.logmaker=INFO
logging.logback.rollingpolicy.file-name-pattern=logs/controller-%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30